spring.application.name=food-autocomplete
spring.datasource.url=jdbc:oracle:thin:@localhost:11521:XE
spring.datasource.username=FIN
spring.datasource.password=!QAZ2wsx
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=60s
OracleDialect
